### ISSUE TITLE
NuPIC model params has invalid parameter for RDSE

### ISSUE THREAD

**Issue by rhyolight** [numenta/NAB#235]
The RDSE configuration has a property called [`numBuckets`](https://github.com/numenta/NAB/blob/master/nab/detectors/numenta/modelParams/model_params.json#L45) that is not an input parameter for the actual RDSE. This is confusing. You can see where this value is removed from the actual model params before creating the model and used as part of the resolution calculation [here](https://github.com/numenta/NAB/blob/master/nab/detectors/numenta/numenta_detector.py#L85-L89). 

I found this confusing, as I assumed that the model params could be used as-is.

**Comment by rhyolight** [comment]
I can totally see why this is done, I just think it could be done in a less confusing way. At least make it clear that the `model_params.json` file cannot be uses directly.

**Comment by BoltzmannBrain** [comment]
The RDSE needs to know what granularity at which to setup the data buckets, and then use this granularity to calculate the resolution on a per file basis. That is, `numBuckets` is specified for the entire corpus, from which the RDSE calculates `resolution` for each data file in the corpus. The fix for #231 will make this a bit cleaner.

**Comment by BoltzmannBrain** [comment]
Closed w/ #236

**Comment by rhyolight** [comment]
Thanks @BoltzmannBrain
