### ISSUE TITLE
Post mean scores for algorithms that use a random seed.

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#245]
Scores should not reflect a single random seed, but rather the mean over a handful of seeds. For algorithms that use a random number generator, we want the scoreboard to reflect the mean score, with a note that indicates the spread.

**Comment by BoltzmannBrain** [comment]
For the random detector I've found the following means and ranges:

- standard: 11.03 (7.95 to 16.83)
- reward_low_FP_rate: 1.2 (-1.56 to 2.14)
- reward_low_FN_rate: 19.5 (11.34 to 23.68)

**Comment by subutai** [comment]
@BoltzmannBrain Let's update the README with these, as well as the results from the Sliding Gaussian threshold detector.

**Comment by mrcslws** [comment]
Suggestion 1: **We should report the mean for HTM as well.**

The NAB score for the HTM detectors varies significantly with different random seeds. Some examples:

- Using the current SP seed (1956), the "numentaTM" detector gets a standard score of 60.7
- With seed 42, it gets 58.3
- With seed 1957, it gets 63.9

Our posted score of 65.3 is just one sample. It would be good to post the mean.

(This score dropped when I [recently](https://github.com/numenta/nupic/pull/3344) removed [this line](https://github.com/mrcslws/nupic/blob/359629d7cf0c1199423ee905d94e806551705c6c/src/nupic/research/spatial_pooler.py#L1271). We're randomly sampling a list, and I just stopped sorting the list. This was essentially the same as changing the random seed. )

________________
  
Suggestion 2: **NAB should have built-in support for running detectors multiple times and measuring the mean.**

With variation like this, it's difficult to use NAB to check whether a change is good or bad. We don't know whether a change actually affects performance, or if it just shuffled the performance of the random seeds.

And if we're going to post mean scores, it would be nice if we could also post the results (e.g. `NAB/results/numentaTM`) that get those scores, so that the scores in the `final_results.json` match the README.

So I think:

- `run.py` should support running a detector multiple times, passing a seed into the detector.
- Results files should contain `anomaly_score` values for multiple runs.
- We'll still use a single threshold for each detector + scoring scheme. We don't need to run the optimizer for each seed.

**Comment by cogmission** [comment]
**Question:** How is it that a stable determinate algorithm varies in _performance_ or _quality_ due to changes in RNG seeds? This doesn't seem right. This is what @rhyolight was talking about in our meeting, that should not be the case. The performance shouldn't vary just because we choose a different seed. 

Also, I question whether the "test" or NAB should be altered to "allow" for this (indeterminate) behavior?

**Comment by BoltzmannBrain** [comment]
@mrcslws NAB detectors should have transparency as to how random seeds affect scores, and how to adjust them if desired. But built-in functionality may be overkill.
