### ISSUE TITLE
HTMJava NAB Scores do not match published scores

### ISSUE THREAD

**Issue by suhasDataken** [numenta/NAB#316]
I cloned latest master branch of NAB and followed suggested steps to run benchmark against htmjava detector. The results I got are as follows:
```python
"htmjava": {
        "reward_low_FN_rate": 60.81038423988505,
        "reward_low_FP_rate": 49.23705903463793,
        "standard": 55.8707487736207
    }
```

Whereas the published scores for htmjava are:

```
reward_low_FN_rate: 70.4
reward_low_FP_rate:53.2
standard : 65.5
```

Did I miss something?

**Comment by rhyolight** [comment]
The published scores are from about 2 years ago. I'm not sure how much htm.java has changed since then, but it could have. If you are running off the master branch the numbers may have changed a bit.  This seems like a pretty big change though. Do you have any ideas @cogmission?

**Comment by cogmission** [comment]
@rhyolight - thanks for looking into this. I think what I was referring to by "2 different ways in which the framework is run" was maybe an optimization present in the Numenta runs or maybe that there were modified versions of the TemporalMemory used or different version? Sorry if I'm adding more confusion! :-P

**Comment by rhyolight** [comment]
@cogmission You never implemented the BacktrackingTM, or did you? My memory, man.

**Comment by cogmission** [comment]
@rhyolight - I heard mention of it somewhere, not sure... but no. Whether this is the right attitude or not, I'm not sure, but I was only going to implement whatever got put in the Nupic code proper? Is the backtracking algo in Nupic or just research?

I don't think I need to implement everything in Research because it might not even make it to the Nupic repo? I'm not sure I should implement stuff that will never be used - so my "trigger" was waiting for stuff to move over from Research to Nupic proper - then I was going to implement everything... 

Is that not the way I should proceed? Is there a way to know what in Research I should probably regard as canon? (I think I asked you this the last time we spoke?)

**Comment by rhyolight** [comment]
@cogmission So we've looked into this, specifically @lscheinkman replicated the reported numbers using HTM.java and the current [instructions](https://github.com/numenta/NAB/tree/master/nab/detectors/htmjava). I am going to create a new PR against NAB to update the scores both @lscheinkman and @suhasDataken got running HTM.java against NAB. 

David, if you'd like to dispute any of this, you'll need to ru-run HTM.java against NAB and see what numbers you get. I've attached the dockerfile Luiz used to replicate the numbers reported in this PR. 

[Dockerfile.txt](https://github.com/numenta/NAB/files/2091874/Dockerfile.txt)

There is certainly a possibility that a specific version of the HTM.Java codebase was used when the numbers were first generated and things have changed over time. If that turns out to be the case we could just note the version of the software used instead of updating the numbers. What do you think David?

**Comment by cogmission** [comment]
@rhyolight Do we know the version of the software used to obtain the original numbers? Also, the new numbers are for the latest version?

@rhyolight Honestly, my only job is to ensure algorithmic parity with whatever version of NuPIC HTM.Java is being developed against at the time. It may be that there are "enhancements" used beyond that which are specifically tailored to enhance the performance of NuPIC on anomaly detection tasks - I don't know? I don't have any investment in keeping HTM.Java's NAB scores in sync with NuPIC's because I can't chase down every use case in which HTM.Java is used.

My only concern is that HTM.Java and NuPIC have absolutely no algorithm differences and yield the same output - which it absolutely did at the time of my last "flogging". :-)  As long as people can use it in any circumstance they can use NuPIC in, with confidence in its identicalness, then I'm fine - because I'm only one person and can't keep up with all the clients it is use with.

Chasing the last sync session did untold things to my psyche :-). Looking at bit by bit of output and coming up with a "universal random number generator", and still not finding why there was a difference. Then to find out that there was a [tweak made outside of the system](https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/model/Connections.java#L51) (in NuPIC's Network API or OPF) which had nothing to do with NuPIC proper - REALLY KILLED ME!  (Though, I look upon it with humor now) :-)

I will get back to it to sync up with the latest version eventually though I was kind of waiting to see when "Research" would be re-integrating back into NuPIC so that I could work on the new version?

**Comment by rhyolight** [comment]
David, it may be because we need to run NAB with the `--optimize` flag, which would explain everything. Standby, you probably don't need to do anything. 

I forgot that you were not even the one to created these numbers in the first place.

**Comment by cogmission** [comment]
@rhyolight - Any word on when/if "Research" will be integrated back into NuPIC proper?

**Comment by rhyolight** [comment]
That's an entirely different discussion! Feel free to bring it up on the forum.

**Comment by cogmission** [comment]
@rhyolight [Ask and you shall receive!](https://discourse.numenta.org/t/research-repository-the-road-ahead/4016)

**Comment by rhyolight** [comment]
Ok, here is the status. The best numbers we are getting now are in #319, including a README update to add `--optimize`. We think the first set of numbers we used were because of a manually chosen random seed, which tends to make a difference. 

So we are going to merge the PR with updated numbers. David there is nothing you need to do here, I am just letting you know that we have to adjust the numbers.
