### ISSUE TITLE
Have you been try to calculate 0000000->1111111?

### ISSUE THREAD

**Issue by FavorMylikes** [numenta/NAB#329]
0000000 is labeled by human
1111111 is labeled by code
What the score of that?
All of false positive seem be counted by your sigmoid code.
And the score is -7*fp_weight.
It looks less than S_null.
Is that right?

**Comment by FavorMylikes** [comment]
Code at NAB/nab/scorer.py line 215 to line 219.
I just wanna reproduce the scale sigmoidal function to compare my result.
And, I don't know why it usually give me a negative score.
weight use tp,fn,fp,tn = (1,1,0.11,1)

**Comment by rhyolight** [comment]
I am studying up on the scoring mechanism. Will be back with a comment tomorrow hopefully.

**Comment by rhyolight** [comment]
@FavorMylikes This scoring logic is likely going to change soon, so I'm going to put this off until #328 is resolved.

**Comment by FavorMylikes** [comment]
Is there anything I can do?

**Comment by rhyolight** [comment]
Sure, can you clarify exactly what you mean by 0000000 and 1111111? And the human / code? I guess I still don't really understand your question.

**Comment by FavorMylikes** [comment]
1 means anomaly,
0000 means there is no anomaly in timeseries
1111 means all of value in timeseries is anomaly.
By human means that there is a man think it is a outlier if the label is 1.
By code means detector think it is a outlier if the label is 1

**Comment by FavorMylikes** [comment]
And
(Human, detector)
(1,1)means truepositive
(0,1)means falsepositive

**Comment by rhyolight** [comment]
Have you read this paper? https://arxiv.org/abs/1510.03336

![img_0335](https://user-images.githubusercontent.com/15566/51130677-6705ec80-17e2-11e9-997b-a81e53327418.jpg)

It explains the logic better than I understand it. The folks who wrote this code are no longer contributing to the repository, but if you are just trying to understand the scoring, you should read that paper.

**Comment by FavorMylikes** [comment]
Yes, sure, I have read it. And follow it found git address.
I think you should know the code is very difference with the paper, there
is no -3 in Python file, it be changed to -1, and so on, I know why he use
sigmoidal function, but you can find why here appears so many issues about
the minus score in the repository, this is the reason why I ask this
question.


On Jan 15, 2019 1:56 AM, "Matthew Taylor" <notifications@github.com> wrote:

Have you read those paper? https://arxiv.org/abs/1510.03336

[image: img_0335]
<https://user-images.githubusercontent.com/15566/51130677-6705ec80-17e2-11e9-997b-a81e53327418.jpg>

It explains the logic better than I understand it. The folks who wrote this
code are no longer contributing to the repository, but if you are just
trying to understand the scoring, you should read that paper.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/numenta/NAB/issues/329#issuecomment-454099609>, or mute
the thread

**Comment by rhyolight** [comment]
@balladeer Maybe you can help me understand this. @FavorMylikes says the current scoring implementation is different from what is in our paper. You have obviously studied this recently, can you comment?

**Comment by balladeer** [comment]
> 0000000 is labeled by human
> 1111111 is labeled by code

I assume that in this example there is no previous anomaly window.  This is important, as the presence of a previous window determines whether we use lines 215-219 for scoring or lines 220-225.

Lines 215-219 are basically just a shortcut to mimic the case of "there was a previous anomaly window, but it was really far back".  That case is handled down on [line 284](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L284).

----
So the usual case (where we are very far to the right of an anomaly window) basically does the following:
1. calculate `relative position` to window ([line 221](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L221))
2. convert `relative position` into `raw score` based on `scaledSigmoid` ([line 259](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L259))
3. multiply the `raw_score` by the profile false positive weight, `fpWeight` ([line 222](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L222))

Note that in step 2, if the `relative distance > 3.0`, then we just return `-1.0` ([line 284](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L284)), so our final score for this point is `-1.0 * fpWeight == -fpWeight`.

Back to lines 215-219: these are performed when there is no previous window to calculate a distance from, which happens if an anomaly is detected before the first true anomaly window, but after the probationary period has ended.  In that case, we directly get a score of `-fpWeight` [line 216](https://github.com/numenta/NAB/blob/master/nab/scorer.py#L216), which is the _same score_ we get if this anomaly point was just really far away from the previous anomaly window.

So, to your original question:

> 0000000 is labeled by human
> 1111111 is labeled by code

Yes, assuming your example comes before all anomaly windows, we do expect this segment to be scored at `-7 * fpWeight`.  Further, we expect this score to be much lower than the `null` detector.  The `null` detector's entire score comes from missing the anomaly windows.  In a file with, say, 2 anomaly windows, the `null` detector's entire score is just `-2 * fnWeight`.  A detector which has a lot of false positive will easily score several orders of magnitude worse than the `null` detector.

Does that help?

**Comment by FavorMylikes** [comment]
Yes！That is what I was talking about.
For randomly detector, it is very possible to generate a all anomaly window
assert.
And the reason in paper  to explain why randomly detector has a positive
score is **optimizer**.
I think you just to adjust the weight let all of value be a anomaly.
It is real bad idea.
My suggest.
Just use sigmoidal function to adjust vector <tp,fp,fn,tn> and recalculate
f1 score.

Zachary T Cross <notifications@github.com> 于2019年1月15日周二 上午9:06写道：
